### ISSUE TITLE
tf2center adblock getting tripped now.

### ISSUE THREAD

**Issue by ghost** [cancerpubs/tf2center-AdBlock#5]
Keeps redirecting to https://tf2center.com/adblock no matter if the plugin is on or off. Tested with uBlock Origin and PiHole both turned off. Using latest version of Firefox at the time of writing.

**Comment by cancerpubs** [comment]
I tested the plugin on my system with the newest FireFox version. It works totally fine for me. 
Give me some time to reproduce your problem so I can fix it.

**Comment by ghost** [comment]
I just tested and it only happens once I am signed into the site via Steam. The main page and lobbies load fine when I am not, although I obviously can't play like that.

Firefox version is 57.0.2, OS is Windows 7 64 bit.

Checked the forums, I don't have a ban from the site. Also double checked the things they mention themselves, such as tracking protection, screen resolution, and hosts file. All of it is correct for accessing tf2center. Only thing I didn't try was disabling anti-virus (Microsoft Security Essentials) which shouldn't matter as it has no browser integration.

The issue may be a problem with the site itself. Using Google Chrome 63.0.3239.108 and only tf2center-adblock plugin I get the same issue, and it persists when I remove the plugin.

**Comment by cancerpubs** [comment]
We updated to the version 1.1.0
This bug should no longer show up again.
Sorry about the long development delay!
